name: Deploy App1

on:
  push:
    paths:
      - 'app1/**' # Trigger only if files in app1 change

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Display message
        run: echo "Deploy for App1 ran"